# Generated by Django 5.0.7 on 2025-06-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_thread_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='thread',
            name='password',
            field=models.CharField(default='temporary_password', max_length=128),
        ),
    ]
