# Generated by Django 5.0.7 on 2025-06-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_thread_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.AlterField(
            model_name='thread',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
