# Generated by Django 5.0.7 on 2025-06-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comment_options_alter_thread_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
