# Generated by Django 5.0.7 on 2025-06-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_thread_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
